### PR TITLE
vulkan: fix compatibility with MoltenVK 1.3.216

### LINKED ISSUE #128: [macOS][MoltenVK] VK_ERROR_INCOMPATIBLE_DRIVER after upgrading to 1.3.216
```
Initialized libplacebo v4.192.0-91-g61f2de1 (API v206)
Attempting to initialize API: SDL2 (vulkan)
Enabling debug meta layer: VK_LAYER_KHRONOS_validation
Enabling debug report extension: VK_EXT_debug_utils
Creating vulkan instance with extensions:
    VK_KHR_get_physical_device_properties2
    VK_KHR_surface
    VK_EXT_swapchain_colorspace
    VK_KHR_external_memory_capabilities
    VK_KHR_external_semaphore_capabilities
    VK_KHR_surface
    VK_MVK_macos_surface
    VK_EXT_debug_utils
  and layers:
    VK_LAYER_KHRONOS_validation
Failed creating instance: VK_ERROR_INCOMPATIBLE_DRIVER
Failed initializing vulkan instance
libplacebo: Failed creating vulkan instance!
No windowing system / graphical API compiled or supported!
```

Was working with 1.3.211.0, so I suspect this is a moltenvk issue, but I can't find what the root cause is.

vulkaninfo:

```
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.216


Instance Extensions: count = 13
-------------------------------
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_metal_surface                   : extension revision 1
VK_EXT_swapchain_colorspace            : extension revision 4
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_portability_enumeration         : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_MVK_macos_surface                   : extension revision 3

Instance Layers: count = 4
--------------------------
VK_LAYER_KHRONOS_profiles         Khronos Profiles layer         1.3.216  version 1
VK_LAYER_KHRONOS_synchronization2 Khronos Synchronization2 layer 1.3.216  version 1
VK_LAYER_KHRONOS_validation       Khronos Validation Layer       1.3.216  version 1
VK_LAYER_LUNARG_api_dump          LunarG API dump layer          1.3.216  version 2

Devices:
========
GPU0:
	apiVersion         = 4198616 (1.1.216)
	driverVersion      = 10110 (0x277e)
	vendorID           = 0x106b
	deviceID           = 0xc0303ef
	deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
	deviceName         = Apple M1 Pro
	driverID           = DRIVER_ID_MOLTENVK
	driverName         = MoltenVK
	driverInfo         = 1.1.10
	conformanceVersion = 0.0.0.0
	deviceUUID         = 0000106b-0c03-03ef-0000-000100000884
	driverUUID         = 4d564b00-0000-277e-0c03-03ef00000000
```

uname -a:

```
Darwin litongzhoudeMacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64 arm Darwin
```

The official demo `vkcube` works as expected

How can I help?

### PR DESCRIPTION
**Pull request by CarterLi**
Fixes #128

### CODE REVIEW

File: src/vulkan/context.c [hunk 1]
```diff
@@ -524,6 +527,9 @@ pl_vk_inst pl_vk_inst_create(pl_log log, const struct pl_vk_inst_params *params)
             .sType = VK_STRUCTURE_TYPE_APPLICATION_INFO,
             .apiVersion = api_ver,
         },
+#ifdef VK_KHR_portability_enumeration
+        .flags = VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR
```
Comment (haasn) [inline src/vulkan/context.c:531]: Should this flag only be set if the `VK_KHR_portability_enumeration` extension was enabled successfully?

**Comment by CarterLi** [comment]
Done

**Comment by haasn** [comment]
LGTM
